### PR TITLE
add reverse finger and intake commands

### PR DESCRIPTION
**Pull request by RuralAnemone**
- **hi**
- **bye**
- **reword tutorial**
- **add reverse intake command**
- **add flinger reverse/intake command**
- **remove unused imports**

### CODE REVIEW

**Comment by RuralAnemone** [comment]
wait I'm dumb

**Comment by RuralAnemone** [comment]
there we go that should be good

**Review by KeithRieck — CHANGES_REQUESTED** [review]
Hi Isaiah,

Your commands look good.  However, we cannot merge this branch into main because it contains the Controls Scheme Manager.

Please checkout the `main` branch and then create a new branch from there.  Copy over your commands and the change to `Constants`.  You will need to create a new PR.

**Comment by RuralAnemone** [comment]
oh true

**Comment by RuralAnemone** [comment]
(:

**Comment by HenryEwald** [comment]
The control scheme manager is required to have a manual mode as requested by the drive team

**Comment by RuralAnemone** [comment]
um

**Pull request closed without merging**
