### PR TITLE
Add mostly all useful logging fields + DS input logging (TEST BEFORE MERGING)

### PR DESCRIPTION
**Pull request by S1ink**

### CODE REVIEW

**Comment by S1ink** [comment]
Added fixes so might wanna merge this sooner

**Review by KeithRieck — APPROVED** [review]
The code is all OK.  

However, this PR appears to be  for a merge in to Sam's fork, rather than the repository's main branch.

**Comment by S1ink** [comment]
Ok I polished everything up now and added all the available motor statistics for the climber, intake, and flinger subsystems (as well as target speed/state variables). Drivebase motors are not being logged since it would get a bit messy and I do not want to rearchitect all of your guys' code just to add this feature. Driverstation inputs are now all logged as well.
@KeithRieck its not a merge into my fork but rather a merge into one of Henry's branches here since that was what we were testing with today. Also sorry if I'm not supposed to be helping... I asked Henry if he wanted me to help add logging since he seemed a little overwhelmed by it, so I am just trying to help out 😀. Hopefully this aids in us feeling so helpless when things go wrong.

**Comment by KeithRieck** [comment]
Old PR.

**Pull request closed without merging**
