### PR TITLE
add reverse finger and intake commands (take 2)

### PR DESCRIPTION
**Pull request by RuralAnemone**
adds manual intake and finger commands, can be toggled for reverseness

### CODE REVIEW

**Comment by KeithRieck** [comment]
So far, so good.   Next, you'll need to commit your changes to this branch, and push the branch up.

One more necessary step will be to test your changes on the robot.  We (or someone) will need to add some simple code into `RobotContainer` to represent the button box and to trigger your commands.   I can work with you on this tonight.

**Comment by RuralAnemone** [comment]
sounds good. it should probably take me like 5 minutes to get the new commands and bindings over to this branch I just need to work on my homework at the moment (:
(hence the draft pr and dummy commit)

**Review by beardedone55 — APPROVED** [review]
This looks good.

**Review by KeithRieck — APPROVED** [review]

**Comment by RuralAnemone** [comment]
incredible

**Pull request merged**
